#!/usr/bin/env bash

PID=`ps -aux | grep -e "[r]omeo_join_captcha.py" | awk 'FNR == 1 {print $2}'`

if [ ! -z "$PID" ]; then
    echo "Already running."
    exit 1
fi

rm -f ./data/captchas/*
nohup python3 -u romeo_join_captcha.py > output.log 2>&1 &
echo "Starting Script..."
sleep 1
./status

exit 0
